# Generated by Django 4.2 on 2023-06-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_remove_productos_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='rutaImagen',
            field=models.TextField(default=' '),
        ),
    ]
