# Generated by Django 4.0.5 on 2023-06-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_productos_rutaimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='categorias',
            field=models.ManyToManyField(through='ecommerce.ProductosPorCategoria', to='ecommerce.categoria'),
        ),
    ]
