# Generated by Django 4.0.5 on 2023-05-21 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medidores', '0001_initial'),
        ('consumos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumos',
            name='medidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medidores.medidores'),
        ),
    ]
