# Generated by Django 4.2 on 2023-05-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumos',
            name='medidor',
            field=models.PositiveIntegerField(),
        ),
    ]
